### ISSUE TITLE
undefined loginToken and Signature

### ISSUE THREAD

**Issue by johnykes** [gochargetech/erdjs-vue#20]
Hi,
When connecting using extension, the `loginToken` is undefined, and when connecting using the xPortal app, both `loginToken` and `Signature` are undefined.
I need them in order to integrate `native-auth-client`, so I can create native tokens and validate them on the backend side.

```
"loginInfoStore": {
    "$id": "erdjs-login-info",
    "loginMethod": "extension",
    "walletConnectLogin": null,
    "ledgerLogin": null,
    "tokenLogin": {
      "loginToken": "undefined",
      "signature": "5d886c7...72402"
    },
    ...
}
```

**Comment by ionvv** [comment]
Implemented in https://github.com/gochargetech/erdjs-vue/commit/de140ce714fb3a2cd4be91d4ab6f575a9d5fb7d5, will be live in upcoming days

**Comment by johnykes** [comment]
Will be the other 2 login methods supported with native auth? I ask because I can see only 2/4 here
```
    extensionLogin: {
      nativeAuth: true
    },
    ledgerLogin: {
      nativeAuth: true
    }
 ```
 
 Also, would be very very cool to have a method like getNativeAuthJwt/Token(), so it will automatically generate a native auth token.

**Comment by ionvv** [comment]
> Will be the other 2 login methods supported with native auth? I ask because I can see only 2/4 here
> 
> ```
> 
>     extensionLogin: {
> 
>       nativeAuth: true
> 
>     },
> 
>     ledgerLogin: {
> 
>       nativeAuth: true
> 
>     }
> 
>  ```
> 
>  
> 
>  Also, would be very very cool to have a method like getNativeAuthJwt/Token(), so it will automatically generate a native auth token.

All of them are supported, you just need to add them in a similar way on init
