### ISSUE TITLE
invalid chain ID

### ISSUE THREAD

**Issue by johnykes** [gochargetech/erdjs-vue#27]
Hi,
Maybe I'm just missing something, but I get "invalid chain ID" on mainnet. xEGLD transfer works perfect on devnet, but when I try to do it on the mainnet, I get this error.

```
const { erdjsVue } = require("erdjs-vue")
const erdjs = erdjsVue(
  {
    loadCss: false,
    chain: "mainnet",
    piniaInstance: pinia
  },
  {
    walletConnectV2ProjectId: "9b1...2d8"
  }
)
app.use(erdjs);
```

```
let tx = {
        receiver: "erd...hd2",
        data: "",
        value: 10000000000000000
      }
// =>{"receiver":"erd...hd2","data":"","value":"10000000000000000"}

      await this.$erdjs.dapp
        .sendTransaction(tx)
        .then(({ sessionId, error }) => {
          if (error) {
            alert(error)
          }
        })
```
=>
```
Uable to send transactions
...
transaction generation failed: invalid chain ID
```

Version: 0.9.10; Vue 3;

Also, it still shows "xEGLD" even if it's on mainnet.
![image](https://user-images.githubusercontent.com/48965850/234023871-9b1999a3-fb9d-4f25-8324-9d8eb87c358a.png)

Q: Do I need a walletconnect server or something?

**Comment by ionvv** [comment]
Fixed in V0.9.14 https://github.com/gochargetech/erdjs-vue/releases/tag/v0.9.14
